repos:
  # Format code with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, css, scss, html, md, yaml, yml]
        additional_dependencies:
          - prettier@3.1.0

  # Lint JavaScript/TypeScript with ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@6.19.0'
          - '@typescript-eslint/parser@6.19.0'

  # Check for merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Validate Astro files
  - repo: https://github.com/withastro/pre-commit-astro
    rev: v0.1.0
    hooks:
      - id: astro-check
      - id: astro-sync
